apiVersion: apps/v1
kind: Deployment
metadata:
  name: presto-worker
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: presto-worker
  template:
    metadata:
      labels:
        app: presto-worker
    spec:
      containers:
      - image: beltranalex928/presto-worker:latest
        name: worker
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: presto-config
            mountPath: /opt/presto/etc/catalog
            subPath: ''
        ports:
        - containerPort: 8080
      volumes:
        - persistentVolumeClaim:
            claimName: presto-config
          name: presto-config
